### PR TITLE
Completed membership tasks

### PR DESCRIPTION
**Pull request by Mnguyener**
Update 'formatMembership()' in 'memberships.ts' to display information from the 'semesters' column as well as if a membership was canceled.
Update 'grantMembership.ts' to stop a membership insertion for a contact who is already a member with a valid membership.

### CODE REVIEW

**Review by mellophone — CHANGES_REQUESTED** [review]
In `grantMemberships.ts`
- Instead of wrapping lines 72-91 in the if-statement, convert line 71 into a guard case with the condition `if(!isAMember.error && isAMember.data[0])` and inside it send the error message you made in line 96 using the `sendError()` function. (See lines 58-65 for reference)

In `memberships.ts`
- Create a variable called `isCanceled` that will determine if the current membership has been canceled before its expected expiration. This can be done by determining if the end date lands on 1/1 or 7/1 or not. If it lands on 1/1 or 7/1 at 12am, then the membership has not been canceled, otherwise it has.
- On line 42, change the field `"Current Member:"` to `"Status:"` that will have the value `"Active"`, `"Expired"`, or `"Canceled"`. This way, we can see the history of each membership and know which one is active if any.

Let me know if you have any follow up questions about any of this. Great work guys!

**Review by mellophone — APPROVED** [review]

**Review by bnleft — CHANGES_REQUESTED** [review]
tasks
- in `admin_commands/grantMembership.ts`, rename `isAMember` to `isMemberResponse`
- in `officer_commands/memberships.ts`, change the ternary operators into if and else statements

notes
- ternary operators shouldn't be nested, it makes it hard to read

good work so far!

**Review by bnleft — CHANGES_REQUESTED** [review]
tasks
- create `isExpired` variable
- create `decideStatus` function that takes in `isCanceled` and `isExpired`

notes
- we want to the `status` variable to be immutable, by using guard if statements with a function

**Review by bnleft — APPROVED** [review]
yay

**Review by Junnyyy — APPROVED** [review]
Looks Good! No changes other than ones brought up by Bryant. One note I agree with is nested ternary operators are difficult to understand and should be avoided.

**Pull request merged**
