### PR TITLE
CougarCS-Bot Version 1.0

### PR DESCRIPTION
**Pull request by mellophone**
## What type of PR is this? (check all applicable)

- [x] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [x] 🔖 Release
- [ ] 🚩 Other

## Description

This PR includes mainly 16 available commands, Supabase functions, and discord logs and reports.
## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [x] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by bnleft — CHANGES_REQUESTED** [review]
tasks:
- add `package-lock.json`
- in `cancelmembership.ts`, instead of `as string`, use `String(...)` conversion
- in `grantmembership.ts`, extract the choices into a different file
- in `grantmembership.ts`, instead of `as string`, use `String(...)` conversion
- in `updatecontact.ts`, extract the list of choices into a different file
- in `updatecontact.ts`, create an interface for `Contact` with all the fields (uh_id, email, ...)
- in `updatecontact.ts`, extract the list of embed fields into its own function
- in `pay.ts`, instead of `as string` and `as number`, use `String(...)` and `Number(...)` conversion
- in `pay.ts`, extract the second condition in line 59 to its own variable
- in `pay.ts`, refactor lines 97 - 160, duplicated code
- in `find.ts`, create an interface for `Member` with all the fields (psid, email, ...)
- in `find.ts`, refactor lines 86-94
- in `find.ts`, extract the list of embed fields into its own function
- in `grant.ts`, extract the list of choices into a different file
- in `grant.ts`, create an interface for MembershipGrant with all the fields
- in `memberships.ts`, create an interface
- in `memberships.ts`, refactor lines 98-113
- in `ping.ts`, add empty lines
- in `pruneexpiredmembers.ts`, refactor, violating `SRP`
- in `rolegiver.ts`, refactor, violating `SRP`
- in `supabaseping.ts` refactor, violating `SRP`
- in `whois.ts`, create an interface for `Member`
- in `whois.ts`, extract the list of embed fields into its own function
- in `whois.ts`, refactor, violating `SRP`
- in `balance.ts`, refactor, violating `SRP`
- in `claim.ts`, refactor, violating `SRP and DRY principle`
- in `leaderboard.ts`, refactor, violating `SRP`
- in `report.ts`, extract the choices into a different file

notes:
- `package-lock.json` should not be removed, it's there to track the entire tree of dependencies and the exact version
- `as type` is a cast annotation that treats the value as a string at compile time, while `Type(...)` conversion handles the type at both compile and run time
	- the problem is regarding the type-safety
	- even if there is no intention of calling any string operations, 
	a server-side application like this bot could possibly break and throw errors
	when other developers decide to work on this project
	- prefer getting compile-time errors than getting run-time errors
- a long list of constant data should be in a different file, this is to reduce code noise
- create interfaces for objects (like `Contact`), reduces code noise and duplicated code
- avoid long and multi-line if conditions, extract into a variable to improve readability
- implement the `DRY` principle, there's a fair bit of duplicated code
- implement `SRP`, the run function should not have many responsibilities, extract pieces of code into smaller functions
- when using lambdas, a good rule of thumb is to keep it one line
- add empty lines to improve readability and section pieces of instructions
- besides branch merge PRs, avoid creating PRs with many changes

experiment:
- For the variables that use discord types, see if using `Type(...)` like `GuildMember(...)` works

awesome work! I looked at the interactions in Testing Grounds, exciting! let me know if you have any questions

**Review by Junnyyy — CHANGES_REQUESTED** [review]
- I would consider camelCase for files instead of lowercase.
- I would split types into a ``types`` directory or something related. Having types in files makes it cluttered and hard to find. Splitting it makes it reusable and easier to maintain.
- A consideration might be to pull options for commands from the database. I'm not sure how feasible it would be to pull on request, but it would make it easier for future officers.
Example: instead of hard coding choices in ``grantmembership`` you pull them from Supabase on demand.

I know Bryant mentioned splitting choices into different files and this follows in line with that.
- in ``whois.ts`` little nitpick but Whois is not spelled as "WhoIs" it's spelled as "Whois" which is an internet protocol.
- in ``intentOptions.ts`` I would use ``GatewayIntentBits`` instead of physical bits. It's easier to understand and know what each bit refers to. 
Example: "GatewayIntentBits.Guilds" instead of the number

Legitimately good work though, it's really great. Thank you for the work!

**Review by bnleft — CHANGES_REQUESTED** [review]
instead of `cache.find()`, use `.fetch(id)` with await when possible
https://discord.js.org/#/docs/main/stable/class/RoleManager?scrollTo=fetch
https://discord.js.org/#/docs/main/stable/class/GuildMemberManager?scrollTo=fetch

good work so far!

**Review by bnleft — CHANGES_REQUESTED** [review]
Extract `sendError` function from all applicable files

**Review by bnleft — APPROVED** [review]

**Review by Junnyyy — APPROVED** [review]
LG! 👍

**Pull request merged**
